---
title: "Database statistics"
author: "Quang Nguyen"
format: 
    html:
        toc: true
editor: visual
---

# Database description

## Loading libraries

Loading requisite libraries

```{r}
#| message: false
library(here)
library(flextable)
library(tidyverse)
library(here)
library(xtable)
```

```{r}
db <- readRDS(here("output", "databases", "db_merged.rds"))
db_nested <- db %>% 
    nest(taxonomic = c(species_tax_id, genus_tax_id)) %>% 
    mutate(pathways = if_else(pathways == "NA", 
                              NA_character_, pathways)) %>%
    mutate(substrate = if_else(substrate == "NA", NA_character_, 
                               substrate))
db_table <- db_nested |>
    pivot_longer(cols =  c(metabolism, gram_stain, pathways, substrate, sporulation, motility, cell_shape)) |> drop_na(value) |>
    group_by(name) |>
    summarise(total_traits = n_distinct(value),
              taxonomic = list(taxonomic)) |>
    mutate(n_species = map_dbl(taxonomic, ~{
        bind_rows(.x) |> pull(species_tax_id) |> n_distinct()
    })) |> 
    mutate(n_genus = map_dbl(taxonomic, ~{
        bind_rows(.x) |> pull(genus_tax_id) |> n_distinct()
    })) |> 
    select(-taxonomic) |> 
    arrange(total_traits, n_species, n_genus)

flextable(db_table)


```

A total of `r db_nested |> pull(taxonomic) |> bind_rows() |> pull(species_tax_id) |> n_distinct()` species and `r db_nested |> pull(taxonomic) |> bind_rows() |> pull(genus_tax_id) |> n_distinct()`
was assigned.  