dada2:
    data:
        ibd_16s: 
            cmd: "denoise-single"
            type: "SampleData[SequencesWithQuality]"
            format: "SingleEndFastqManifestPhred33V2"
            manifest: "metadata/ibd_qiime2_manifest.tsv"
            params: "--p-trunc-len 160 \
                    --p-max-ee 2" 
        crc_16s: 
            cmd: "denoise-paired"
            type: "SampleData[PairedEndSequencesWithQuality]"
            format: "PairedEndFastqManifestPhred33V2"
            manifest: "metadata/crc_qiime2_metadata.tsv"
            params: "--p-trunc-len-f 235 --p-trunc-len-r 225 \
                    --p-max-ee-f 2 --p-max-ee-r 2"
predict:
    ibd_16s_picrust2:
        feat_path: "data/pred_picrust2_ibd_feat.csv"
        meta_path: "data/pred_picrust2_ibd_metadata.csv"
        clr_trans: True
        outcome_label: "diseasesubtype"
        pos_class: "CD"
    ibd_16s_trait:
        feat_path: "data/trait_ibd_16s_feat.csv"
        meta_path: "data/pred_picrust2_ibd_metadata.csv"
        clr_trans: False
        outcome_label: "diseasesubtype"
        pos_class: "CD"
    ibd_wgs_pathways:
        feat_path: "data/pred_pathway_ibd_feat.csv"
        meta_path: "data/pred_pathway_ibd_metadata.csv"
        clr_trans: True
        outcome_label: "study_condition"
        pos_class: "IBD"
    ibd_wgs_trait:
        feat_path: "data/trait_ibd_wgs_feat.csv"
        meta_path: "data/pred_pathway_ibd_metadata.csv"
        clr_trans: False
        outcome_label: "study_condition"
        pos_class: "IBD"
    crc_16s_picrust2:
        feat_path: "data/pred_picrust2_crc_feat.csv"
        meta_path: "data/pred_picrust2_crc_metadata.csv"
        clr_trans: True
        outcome_label: "diagnosis"
        pos_class: "Cancer"
    crc_16s_trait: 
        feat_path: "data/trait_crc_16s_feat.csv"
        meta_path: "data/pred_picrust2_crc_metadata.csv"
        clr_trans: False
        outcome_label: "diagnosis"
        pos_class: "Cancer"
    crc_wgs_pathways:
        feat_path: "data/pred_pathway_crc_feat.csv"
        meta_path: "data/pred_pathway_crc_metadata.csv"
        clr_trans: True
        outcome_label: "study_condition"
        pos_class: "CRC"
    crc_wgs_trait:
        feat_path: "data/trait_crc_wgs_feat.csv"
        meta_path: "data/pred_pathway_crc_metadata.csv"
        clr_trans: False
        outcome_label: "study_condition"
        pos_class: "CRC"
coverage:
    16s: "genus"
    wgs: "species"
    
            
